const Status = {
  NOT_FOUND: "Nada encontrado!",
  ID_NOT_FOUND: "Campo ID não encontrado!",
  REQUIRED_FIELD: "Dados faltando!",
  INVALID_EMAIL: "E-mail inválido!",
  INVALID_PASSWORD: "Senha inválida!",
  INVALID_PHONE: "Telefone inválido!",
  INVALID_ID: "Id inválido!",
  USER_ALREADY_EXIST: "Usuário já existe!",
  ROLE_ALREADY_EXIST: "Role já existe!",
  EMAIL_ALREADY_EXIST: "E-mail já existe!",
  USER_ROLE: "Usuário já possui esta role!",
  USER_NOT_FOUND: "Usuário não encontrado!",
  USER_ROLE_ALREADY_EXIST: "UserRole já existe!",
  COMPANY_ROLE_ALREADY_EXIST: "Empresa já existe!",
  USER_ADDRESS_ALREADY_EXIST: "Usuário já possui endereço!",
  COMPANY_ADDRESS_ALREADY_EXIST: "Empresa já possui endereço!",
  USER_ALREADY_HAVE_PHONE: "Usuário já possui telefone!",
  COMPANY_ALREADY_HAVE_PHONE: "Empresa já possui telefone!",
  CREATION_ERROR_TOKEN: "Erro ao criar o token!",
  EXPIRED_SESSION: "Sessão expirada!",
  INVALID_TOKEN: "Token inválido!",
  REQUIRED_TOKEN: "Token não enviado!",
  PHONE_ALREADY_EXIST: "Telefone já existe!",
  CNPJ_ALREADY_EXIST: "CNPJ já existe!",
  INVALID_DATA: "Dados Inválidos!",
  INVALID_CNPJ: "CNPJ inválido!",
  SUCCESS: "Sucesso!",
  CATEGORY_ALREADY_EXIST: "Categoria já existe!",
  FILE_TOO_LARGE: "Tamanho de arquivo inválido!",
  INVALID_PAGE_COUNT: "Número de paginas inválida!",
};

export { Status };
