const Erros = {
  NOT_FOUND: "Nada encontrado!",
  ID_NOT_FOUND: "Campo ID não encontrado!",
  REQUIRED_FIELD: "Dados faltando!",
  INVALID_EMAIL: "E-mail invalido!",
  INVALID_PASSWORD: "Senha invalida!",
  INVALID_PHONE: "Telefone invalido!",
  USER_ALREADY_EXIST: "Usuário já existe!",
  ROLE_ALREADY_EXIST: "Role já existe!",
  USER_ROLE: "Usuário já possui esta role!",
  USER_NOT_FOUND: "Usuário não encontrado!",
  USER_ROLE_ALREADY_EXIST: "UserRole já existe!",
  COMPANY_ROLE_ALREADY_EXIST: "Empresa já existe!",
  USER_ADDRESS_ALREADY_EXIST: "Usuário já possui endereço!",
  USER_ALREADY_HAVE_PHONE: "Usuário já possui telefone!",
  CREATION_ERROR_TOKEN: "Erro ao criar o token!",
  EXPIRED_SESSION: "Sessão expirada!",
  INVALID_TOKEN: "Token invalido!",
  REQUIRED_TOKEN: "Token não enviado!",
  PHONE_ALREADY_EXIST: "Telefone já existe!",
  CNPJ_ALREADY_EXIST: "CNPJ já existe!",
  IE_ALREADY_EXIST: "Inscrição estadual já existe!",
  INVALID_DATA: "Dados Invalidos!",
  INVALID_CNPJ: "CNPJ invalido!",
  SUCCESS: "Sucesso!",
};

export { Erros };
